export interface Payment {
  id: string;
  billingRecordId: string;
  billingRecordNumber: string;
  amount: number;
  paymentDate: string;
  paymentMethod: "cash" | "credit_card" | "bank_transfer" | "check" | "wallet";
  referenceNumber: string;
  chargeType: string;
  status: "paid" | "refunded";
  notes?: string;
  payer: {
    citizenName: string;
    accountId: string;
    taxId: string;
    email: string;
    phone: string;
    address: string;
    billingAddress: string;
  };
}

// TODO: Datos de prueba vinculados a BillingRecords
export const mockPaymentsData: Payment[] = [
  {
    id: "TRX-001",
    billingRecordId: "1",
    billingRecordNumber: "#INV-001",
    amount: 5000,
    paymentDate: "2024-03-15T10:30:00Z",
    paymentMethod: "bank_transfer",
    referenceNumber: "BT-99203348",
    chargeType: "subscription",
    status: "paid",
    notes: "Full payment received via wire transfer.",
    payer: {
      citizenName: "José Antonio Méndez Morales",
      accountId: "#ACT-001",
      taxId: "TX-99001122",
      email: "finance@miche.com.gt",
      phone: "+502 5555 0101",
      address: "12 Calle 4-55 Zona 10, Guatemala City",
      billingAddress: "Apartado Postal 456, Guatemala City",
    },
  },
  {
    id: "TRX-002",
    billingRecordId: "5",
    billingRecordNumber: "#INV-005",
    amount: 8900,
    paymentDate: "2024-03-16T14:20:00Z",
    paymentMethod: "credit_card",
    referenceNumber: "CC-88273911",
    chargeType: "consulting",
    status: "paid",
    notes: "Payment processed via corporate card.",
    payer: {
      citizenName: "Leticia del Valle Escobedo",
      accountId: "#ACT-005",
      taxId: "TX-99005566",
      email: "l.escobedo@gmail.com",
      phone: "+502 4433 0505",
      address: "7-89 Avenida Las Américas, Guatemala",
      billingAddress: "7-89 Avenida Las Américas, Guatemala",
    },
  },
  {
    id: "TRX-003",
    billingRecordId: "9",
    billingRecordNumber: "#INV-009",
    amount: 7800,
    paymentDate: "2024-03-17T09:15:00Z",
    paymentMethod: "wallet",
    referenceNumber: "WL-77112233",
    chargeType: "subscription",
    status: "paid",
    notes: "Mobile wallet payment.",
    payer: {
      citizenName: "Ricardo Alfonso Pérez García",
      accountId: "#ACT-009",
      taxId: "TX-99009900",
      email: "ricardo.perez@gmail.com",
      phone: "+502 9900 0909",
      address: "456 Vista Hermosa, Guatemala",
      billingAddress: "456 Vista Hermosa, Guatemala",
    },
  },
  {
    id: "TRX-004",
    billingRecordId: "1",
    billingRecordNumber: "#INV-001",
    amount: 5000,
    paymentDate: "2024-03-18T16:45:00Z",
    paymentMethod: "bank_transfer",
    referenceNumber: "REF-55443322",
    chargeType: "subscription",
    status: "refunded",
    notes: "Refund processed due to duplicate charge.",
    payer: {
      citizenName: "José Antonio Méndez Morales",
      accountId: "#ACT-001",
      taxId: "TX-99001122",
      email: "finance@miche.com.gt",
      phone: "+502 5555 0101",
      address: "12 Calle 4-55 Zona 10, Guatemala City",
      billingAddress: "Apartado Postal 456, Guatemala City",
    },
  },
  {
    id: "TRX-005",
    billingRecordId: "12",
    billingRecordNumber: "#INV-012",
    amount: 1200,
    paymentDate: "2024-03-20T11:00:00Z",
    paymentMethod: "cash",
    referenceNumber: "CSH-100293",
    chargeType: "maintenance",
    status: "paid",
    notes: "Over the counter payment.",
    payer: {
      citizenName: "Juana Ines",
      accountId: "#ACT-012",
      taxId: "TX-99012345",
      email: "juana.ines@example.com",
      phone: "+502 5555 5555",
      address: "12 Calle 4-55 Zona 10, Guatemala City",
      billingAddress: "Apartado Postal 456, Guatemala City",
    },
  },
  {
    id: "TRX-006",
    billingRecordId: "25",
    billingRecordNumber: "#INV-025",
    amount: 15000,
    paymentDate: "2024-03-21T09:30:00Z",
    paymentMethod: "bank_transfer",
    referenceNumber: "BT-44556677",
    chargeType: "freight",
    status: "paid",
    notes: "International wire transfer.",
    payer: {
      citizenName: "Gloria Esperanza Ortiz",
      accountId: "#ACT-025",
      taxId: "TX-99025025",
      email: "g.ortiz@gmail.com",
      phone: "+502 2525 2525",
      address: "500 Calzada Roosevelt, Guatemala",
      billingAddress: "500 Calzada Roosevelt, Guatemala",
    },
  },
  {
    id: "TRX-007",
    billingRecordId: "3",
    billingRecordNumber: "#INV-003",
    amount: 4500,
    paymentDate: "2024-03-22T15:15:00Z",
    paymentMethod: "check",
    referenceNumber: "CHK-778899",
    chargeType: "consulting",
    status: "refunded",
    notes: "Returned check.",
    payer: {
      citizenName: "Marta Isabel Cabrera",
      accountId: "#ACT-003",
      taxId: "TX-99003344",
      email: "m.cabrera@abc.com",
      phone: "+502 3344 0303",
      address: "200 Calle Real, Antigua",
      billingAddress: "200 Calle Real, Antigua",
    },
  },
  {
    id: "TRX-008",
    billingRecordId: "40",
    billingRecordNumber: "#INV-040",
    amount: 2200,
    paymentDate: "2024-03-23T10:45:00Z",
    paymentMethod: "bank_transfer",
    referenceNumber: "BT-11223344",
    chargeType: "utilities",
    status: "paid",
    notes: "Automatic monthly bill pay.",
    payer: {
      citizenName: "Carlos Enrique Rodas",
      accountId: "#ACT-040",
      taxId: "TX-99040404",
      email: "c.rodas@gmail.com",
      phone: "+502 4040 4040",
      address: "Avenida Reforma 4-55, Guatemala City",
      billingAddress: "Avenida Reforma 4-55, Guatemala City",
    },
  },
  {
    id: "TRX-009",
    billingRecordId: "101",
    billingRecordNumber: "#INV-101",
    amount: 3100,
    paymentDate: "2024-03-24T13:00:00Z",
    paymentMethod: "credit_card",
    referenceNumber: "CC-55667788",
    chargeType: "electricity",
    status: "paid",
    notes: "Paid via online portal.",
    payer: {
      citizenName: "Patricia Noemí Aguilar",
      accountId: "#ACT-101",
      taxId: "TX-99101101",
      email: "p.aguilar@gmail.com",
      phone: "+502 1010 1010",
      address: "99 Kilómetro 15 Carretera a El Salvador",
      billingAddress: "99 Kilómetro 15 Carretera a El Salvador",
    },
  },
  {
    id: "TRX-010",
    billingRecordId: "55",
    billingRecordNumber: "#INV-055",
    amount: 950,
    paymentDate: "2024-03-25T11:30:00Z",
    paymentMethod: "cash",
    referenceNumber: "CSH-556677",
    chargeType: "gardening",
    status: "paid",
    notes: "Seasonal cleanup fee.",
    payer: {
      citizenName: "Luis Fernando Castillo",
      accountId: "#ACT-055",
      taxId: "TX-99055055",
      email: "l.castillo@gmail.com",
      phone: "+502 5555 5555",
      address: "1 Calle de los Alisos, Chimaltenango",
      billingAddress: "1 Calle de los Alisos, Chimaltenango",
    },
  },
  {
    id: "TRX-011",
    billingRecordId: "88",
    billingRecordNumber: "#INV-088",
    amount: 6200,
    paymentDate: "2024-03-26T16:20:00Z",
    paymentMethod: "bank_transfer",
    referenceNumber: "BT-88990011",
    chargeType: "property_tax",
    status: "paid",
    notes: "Quarterly property tax payment.",
    payer: {
      citizenName: "Claudia Victoria Fuentes",
      accountId: "#ACT-088",
      taxId: "TX-99088088",
      email: "c.fuentes@gmail.com",
      phone: "+502 8888 8888",
      address: "Final de la 20 Calle, Zona 10",
      billingAddress: "Final de la 20 Calle, Zona 10",
    },
  },
  {
    id: "TRX-012",
    billingRecordId: "99",
    billingRecordNumber: "#INV-099",
    amount: 1100,
    paymentDate: "2024-03-27T09:00:00Z",
    paymentMethod: "wallet",
    referenceNumber: "WL-99001122",
    chargeType: "membership",
    status: "paid",
    notes: "Annual membership renewal.",
    payer: {
      citizenName: "Héctor Rolando Solís",
      accountId: "#ACT-099",
      taxId: "TX-99099099",
      email: "h.solis@biblioteca.org.gt",
      phone: "+502 9999 9999",
      address: "10 Calle 10-25 Zona 1, Guatemala",
      billingAddress: "10 Calle 10-25 Zona 1, Guatemala",
    },
  },
];
