export interface Municipality {
  id: string;
  municipalityName: string;
  region: string;
  contactPerson: string;
  contactPhone: string;
  contactEmail: string;
  taxId: string;
  logo: string;
  websiteUrl: string;
  status: "active" | "inactive";
  primaryColor?: string;
  secondaryColor?: string;
}

// TODO: Datos de prueba
export const mockMunicipalitiesData: Municipality[] = [
  {
    id: "#MNP-0001",
    municipalityName: "Municipalidad 1",
    region: "Region 1",
    contactPerson: "Persona 1",
    contactPhone: "12345678",
    contactEmail: "persona1@ejemplo.com",
    taxId: "12345678",
    logo: "logo1.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "active",
  },
  {
    id: "#MNP-0002",
    municipalityName: "Municipalidad 2",
    region: "Region 2",
    contactPerson: "Persona 2",
    contactPhone: "12345678",
    contactEmail: "persona2@ejemplo.com",
    taxId: "12345678",
    logo: "logo2.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "inactive",
  },
  {
    id: "#MNP-0003",
    municipalityName: "Municipalidad 3",
    region: "Region 3",
    contactPerson: "Persona 3",
    contactPhone: "12345678",
    contactEmail: "persona3@ejemplo.com",
    taxId: "12345678",
    logo: "logo3.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "active",
  },
  {
    id: "#MNP-0004",
    municipalityName: "Municipalidad 4",
    region: "Region 4",
    contactPerson: "Persona 4",
    contactPhone: "12345678",
    contactEmail: "persona4@ejemplo.com",
    taxId: "12345678",
    logo: "logo4.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "inactive",
  },
  {
    id: "#MNP-0005",
    municipalityName: "Municipalidad 5",
    region: "Region 5",
    contactPerson: "Persona 5",
    contactPhone: "12345678",
    contactEmail: "persona5@ejemplo.com",
    taxId: "12345678",
    logo: "logo5.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "active",
  },
  {
    id: "#MNP-0006",
    municipalityName: "Municipalidad 6",
    region: "Region 6",
    contactPerson: "Persona 6",
    contactPhone: "12345678",
    contactEmail: "persona6@ejemplo.com",
    taxId: "12345678",
    logo: "logo6.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "inactive",
  },
  {
    id: "#MNP-0007",
    municipalityName: "Municipalidad 7",
    region: "Region 7",
    contactPerson: "Persona 7",
    contactPhone: "12345678",
    contactEmail: "persona7@ejemplo.com",
    taxId: "12345678",
    logo: "logo7.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "active",
  },
  {
    id: "#MNP-0007",
    municipalityName: "Municipalidad 7",
    region: "Region 7",
    contactPerson: "Persona 7",
    contactPhone: "12345678",
    contactEmail: "persona7@ejemplo.com",
    taxId: "12345678",
    logo: "logo7.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "active",
  },
  {
    id: "#MNP-0008",
    municipalityName: "Municipalidad 8",
    region: "Region 8",
    contactPerson: "Persona 8",
    contactPhone: "12345678",
    contactEmail: "persona8@ejemplo.com",
    taxId: "12345678",
    logo: "logo8.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "active",
  },
  {
    id: "#MNP-0009",
    municipalityName: "Municipalidad 9",
    region: "Region 9",
    contactPerson: "Persona 9",
    contactPhone: "12345678",
    contactEmail: "persona9@ejemplo.com",
    taxId: "12345678",
    logo: "logo9.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "active",
  },
  {
    id: "#MNP-0010",
    municipalityName: "Municipalidad 10",
    region: "Region 10",
    contactPerson: "Persona 10",
    contactPhone: "12345678",
    contactEmail: "persona10@ejemplo.com",
    taxId: "12345678",
    logo: "logo10.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "active",
  },
  {
    id: "#MNP-0011",
    municipalityName: "Municipalidad 11",
    region: "Region 11",
    contactPerson: "Persona 11",
    contactPhone: "12345678",
    contactEmail: "persona11@ejemplo.com",
    taxId: "12345678",
    logo: "logo11.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "active",
  },
  {
    id: "#MNP-0012",
    municipalityName: "Municipalidad 12",
    region: "Region 12",
    contactPerson: "Persona 12",
    contactPhone: "12345678",
    contactEmail: "persona12@ejemplo.com",
    taxId: "12345678",
    logo: "logo12.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "active",
  },
  {
    id: "#MNP-0013",
    municipalityName: "Municipalidad 13",
    region: "Region 13",
    contactPerson: "Persona 13",
    contactPhone: "12345678",
    contactEmail: "persona13@ejemplo.com",
    taxId: "12345678",
    logo: "logo13.png",
    websiteUrl: "https://www.ejemplo.com",
    status: "active",
  },
];
